runner: "jenkins-jenkins-agent"

trigger:
  push:
    branches: ["main", "feature/*"]
    tags: ["v*", "release-?"]
  merge_request:
    target_branches: ["feature/*", "main"]
    actions:
    - open 
    - reopen
    - comment: ["recheck", "please check this shit"]
    - update: ["commit", "title", "assignee", "description"]
    
stages:
  - name: Run First Stage
    steps:
      - sh: echo "Stage 1"


  - name: Run Tests
    parallel: true
    blocks:
      - name: Unittest
        steps:
          - sh: ls -lh 
              
      - name: Integration Test
        steps:
          - sh: echo "HEHEEH"
          
finally: 
  - sh: echo "Pipeline finished"  